name: florida_state_parks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/fl.png

flutter:
  uses-material-design: true

  assets:
    - assets/florida_parks.json
    - assets/parks_data.json
    - assets/parks_data_with_coords.json
    - assets/fl.png

